set linesize 555;
set serveroutput on; 
SPOOL NN_SDB_PGN_MOTIVO_TRAMITE.out; 
--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
-------------------------------
---SDB_PGN_MOTIVO_TRAMITE
-------------------------------
/*
Se insertan por peticion de Paula Cortes correo del 20210917
*/
--------------------------------------------------------------------------------------------------------------------------------
REM INSERTING into SDB_PGN_MOTIVO_TRAMITE
SET DEFINE OFF;
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE ,ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ESTADO, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, DECISION_CALIFICACION, ID_USUARIO_CREACION, IP_CREACION, FECHA_CREACION, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO) 
VALUES('43615','111','40','DEVOLVER A BUSCADOR ANTIGUO SISTEMA CIRCULO REGISTRAL ORIGEN','A','102','XRP','N','EXC', NULL, user,NULL, SYSTIMESTAMP,'1','14','1');

INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE ,ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ESTADO, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, DECISION_CALIFICACION, ID_USUARIO_CREACION, IP_CREACION, FECHA_CREACION, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO) 
VALUES('43616','111','40','DEVOLVER A BUSCADOR ANTIGUO SISTEMA CIRCULO REGISTRAL ORIGEN','A','102','XRP','N','EXC', NULL, user,NULL, SYSTIMESTAMP,'1','9','1');

INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE ,ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ESTADO, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, DECISION_CALIFICACION, ID_USUARIO_CREACION, IP_CREACION, FECHA_CREACION, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO) 
VALUES('43617','111','40','DEVOLVER A BUSCADOR ANTIGUO SISTEMA CIRCULO REGISTRAL ORIGEN','A','102','XRP','N','EXC', NULL, user,NULL, SYSTIMESTAMP,'1','10','1');

INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE ,ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ESTADO, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, DECISION_CALIFICACION, ID_USUARIO_CREACION, IP_CREACION, FECHA_CREACION, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO) 
VALUES('43618','111','40','DEVOLVER A BUSCADOR ANTIGUO SISTEMA CIRCULO REGISTRAL ORIGEN','A','102','XRP','N','EXC', NULL, user,NULL, SYSTIMESTAMP,'1','11','1');
commit;
--------------------------------------------------------------------------------------------------------------------------------
SPOOL OFF