set linesize 555;
set serveroutput on; 
SPOOL NN_INSERT_SDB_PGN_ETAPA.out;

Insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) 
values ('835','PROCESO DE ENVIO DOCUMENTOS EJECUCION VISITAS','PROCESO DE ENVIO DOCUMENTOS PARA EJECUCION VISITAS','A','N','N','N',null,user,systimestamp,NULL,null,'300','B','H','5','N');
