REM INSERTING into SDB_PGN_ETAPA
set linesize 555;
set serveroutput on; 
SPOOL NN_INSERT_SDB_PGN_ETAPA.out;


BEGIN
    insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (870,'FINALIZACION PROCESO DE VISITAS','FINALIZACION PROCESO DE VISITAS','A','N','N','N',30,'wilmarmoreno',SYSTIMESTAMP,null,null,'192.168.100.2',null,'N',250,'B','H',30,'N');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    delete from SDB_PGN_ETAPA where id_etapa = 870;
	insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (870,'FINALIZACION PROCESO DE VISITAS','FINALIZACION PROCESO DE VISITAS','A','N','N','N',30,'wilmarmoreno',SYSTIMESTAMP,null,null,'192.168.100.2',null,'N',250,'B','H',30,'N');
END;
/
BEGIN
    insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (850,'RESPONSABLE SEGUIMIENTO','RESPONSABLE SEGUIMIENTO','A','S','S','S',null,'C##ADM_WORKFLOW_ENGINE2020',SYSTIMESTAMP,'catherine.robledo',SYSTIMESTAMP,null,'10.11.254.55','N',10,'B',null,null,'S');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    delete from SDB_PGN_ETAPA where id_etapa = 850;
	insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (850,'RESPONSABLE SEGUIMIENTO','RESPONSABLE SEGUIMIENTO','A','S','S','S',null,'C##ADM_WORKFLOW_ENGINE2020',SYSTIMESTAMP,'catherine.robledo',SYSTIMESTAMP,null,'10.11.254.55','N',10,'B',null,null,'S');
END;
/

BEGIN
    insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (845,'FIRMA Y APROBACION SUPERINTENDENTE','FIRMA Y APROBACION SUPERINTENDENTE','A','S','S','S',null,'C##ADM_WORKFLOW_ENGINE2020',SYSTIMESTAMP,'catherine.robledo',SYSTIMESTAMP,null,'10.11.254.55','N',10,'B',null,null,'S');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    delete from SDB_PGN_ETAPA where id_etapa = 845;
	insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values (845,'FIRMA Y APROBACION SUPERINTENDENTE','FIRMA Y APROBACION SUPERINTENDENTE','A','S','S','S',null,'C##ADM_WORKFLOW_ENGINE2020',SYSTIMESTAMP,'catherine.robledo',SYSTIMESTAMP,null,'10.11.254.55','N',10,'B',null,null,'S');
END;
/


