REM INSERTING into SDB_PGN_ETAPA
set linesize 555;
set serveroutput on; 
SPOOL NN_INSERT_SDB_PGN_ETAPA.out;

BEGIN
	Insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values ('295','SUSPENSIÓN TURNO DE VISITAS','SUSPENSIÓN TURNO DE VISITAS','A','N','N','N','30','wilmarmoreno',SYSTIMESTAMP,null,null,'192.168.100.2',null,'N','250','B','H','30','N');
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
	delete from SDB_PGN_ETAPA where id_etapa = 295;
	Insert into SDB_PGN_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ESTADO,INDICADOR_PESO,INDICADOR_BLOQUEO,INDICADOR_DESBORDE,DIAS_HABILES_NORMAL,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,INDICADOR_TOPE,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR) values ('295','SUSPENSIÓN TURNO DE VISITAS','SUSPENSIÓN TURNO DE VISITAS','A','N','N','N','30','wilmarmoreno',SYSTIMESTAMP,null,null,'192.168.100.2',null,'N','250','B','H','30','N');
END;
/
