set linesize 555;
set serveroutput on; 
SPOOL NN_SDB_PGN_ETAPA.out;
------------------------------------------------------------------------------------------------
-- Duvan Beltran
INSERT INTO SDB_PGN_ETAPA(ID_ETAPA, NOMBRE, DESCRIPCION, ESTADO, INDICADOR_PESO, INDICADOR_BLOQUEO,INDICADOR_DESBORDE,ID_USUARIO_CREACION,FECHA_CREACION,ID_FASE,TIPO_REPARTO,ID_UNIDAD_TIEMPO_ESPERA,CANTIDAD_TIEMPO_ESPERA,GENERAR_QR)
VALUES('841','CREACION DE TURNO DE PLAN DE MEJORAMIENTO','CREACION DE TURNO DE PLAN DE MEJORAMIENTO','A','N','N','N',user,SYSTIMESTAMP,'300','B','H','5','N');
/