set linesize 555;
set serveroutput on; 
SPOOL NN_SDB_PGN_MOTIVO_TRAMITE.out;
------------------------------------------------------------------------------------------------
-- correccion Leidy 19/01/2022
BEGIN
	UPDATE SDB_PGN_MOTIVO_TRAMITE 
	SET ID_ETAPA_POSTERIOR = '280'
	, DESCRIPCION = 'SUSPENSIÓN TEMPORAL DEL TRÁMITE DE REGISTRO' 
	WHERE ID_ETAPA_ORIGEN = '203' 
	AND ID_ETAPA_POSTERIOR = '281';
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR ACTUALIZANDO: SDB_PGN_MOTIVO_TRAMITE 203 A 281' || SQLERRM);
	ROLLBACK;
END;
/
--Solicitud Natalia 19/01/2022
BEGIN
	update sdb_pgn_motivo_tramite
	set ID_ETAPA_POSTERIOR = 20
	,ESTADO_ACTIVIDAD = 'ESP'
	WHERE ID_PROCESO = '5'
	AND ID_SUBPROCESO = '2'
	AND VERSION_SUBPROCESO = 1
	AND ID_ETAPA_ORIGEN = 350
	AND ID_MOTIVO = 20
	AND ID_ETAPA_POSTERIOR = 350
	AND ESTADO_ACTIVIDAD = 'XRP';
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR ACTUALIZANDO: SDB_PGN_MOTIVO_TRAMITE PROCESO 5 SUBPROCESO 2 DE 350 A 350' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	update sdb_pgn_motivo_tramite
	set ID_ETAPA_POSTERIOR = 20
	,ESTADO_ACTIVIDAD = 'ESP'
	WHERE ID_PROCESO = '5'
	AND ID_SUBPROCESO = '3'
	AND VERSION_SUBPROCESO = 1
	AND ID_ETAPA_ORIGEN = 350
	AND ID_MOTIVO = 20
	AND ID_ETAPA_POSTERIOR = 350
	AND ESTADO_ACTIVIDAD = 'XRP';
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR ACTUALIZANDO: SDB_PGN_MOTIVO_TRAMITE PROCESO 5 SUBPROCESO 3 DE 350 A 350' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	update sdb_pgn_motivo_tramite
	set ID_ETAPA_POSTERIOR = 20
	,ESTADO_ACTIVIDAD = 'ESP'
	WHERE ID_PROCESO = '5'
	AND ID_SUBPROCESO = '4'
	AND VERSION_SUBPROCESO = 1
	AND ID_ETAPA_ORIGEN = 350
	AND ID_MOTIVO = 20
	AND ID_ETAPA_POSTERIOR = 350
	AND ESTADO_ACTIVIDAD = 'XRP';
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR ACTUALIZANDO: SDB_PGN_MOTIVO_TRAMITE PROCESO 5 SUBPROCESO 4 DE 350 A 350' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','1',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',20,'ESP','N','PAR','','','','A',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43791 DE 350 A 20' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','1',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',200,'XRP','N','PAR','','','','A',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43795 DE 350 A 20' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','2',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',20,'ESP','N','PAR','','','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43792 DE 350 A 20' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','2',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',200,'XRP','N','PAR','','','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43796 DE 350 A 200' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','3',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',20,'ESP','N','PAR','','NULL','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43793 DE 350 A 20' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','3',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',200,'XRP','N','PAR','','NULL','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43797 DE 350 A 200' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','4',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',20,'ESP','N','PAR','','','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43794 DE 350 A 20' || SQLERRM);
	ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION) 
	VALUES (SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'5','4',1,350,100,'GENERAR LIQUIDACION ENTREGA ORIP',200,'XRP','N','PAR','','','','I',user,systimestamp,NULL);
	EXCEPTION WHEN OTHERS THEN 
	DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_PGN_MOTIVO_TRAMITE ID MOTIVO 43798 DE 350 A 200' || SQLERRM);
	ROLLBACK;
END;
/
