set linesize 555;
set serveroutput on; 
SPOOL NN_SDB_ACC_SUBPROCESO.out; 
------------------------------------------------------------------------------------------------
BEGIN
	INSERT INTO SDB_ACC_SUBPROCESO (ID_PROCESO,ID_SUBPROCESO,NOMBRE,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION,ACTIVO) 
	VALUES ('62','6','PLAN DE MEJORAMIENTO',USER,SYSTIMESTAMP,NULL,'S');
	COMMIT;
  EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_ACC_SUBPROCESO 62,6' || SQLERRM);
      ROLLBACK;
END;
/
BEGIN
	INSERT INTO SDB_ACC_SUBPROCESO_VERSION (ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_INICIAL, ESTADO_ACTIVIDAD, SOLICITUD_CERTIFICADO, PLANTILLA, CONSERVACION_DOCUMENTAL, OBTENER_RECIBO_CAJA, ID_USUARIO_CREACION, FECHA_CREACION, IP_CREACION, ESTADO_FLUJO, TIEMPO_VENCIMIENTO, ID_UNIDAD_TIEMPO)
	VALUES                                 ('62'      ,'6'           ,1                  ,10               ,'ASG'            ,NULL                  ,NULL      ,'N'                     ,'N'                 , USER               ,SYSTIMESTAMP   , NULL       ,NULL         ,NULL               ,NULL,NULL )
	COMMIT;
  EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO: SDB_ACC_SUBPROCESO_VERSION 62,6,'|| SQLERRM);
      ROLLBACK;
END;
/