set linesize 555;
set serveroutput on; 
SPOOL NN_02_SDB_PGN_MOTIVO_TRAMITE.out; 
------------------------------------------------------------------------------------------------

INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,10,10,'INICIO PLAN DE MEJORAMIENTO',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,830,10,'GENERACION DE DOCUMENTOS ENVIO A OWCC',835,'AUT','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,830,310,'GENRACION INFORME FINAL',835,'AUT','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,830,320,'GENERACION INFORME SEMANAL',835,'AUT','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,830,330,'GENERACION INFORME INTERVENCION ',835,'AUT','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,830,340,'GENERACION AVISO CONVOCATORIA ',835,'AUT','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,140,'FIRMA Y APROBACION LIDER - RESOLUCION_PRORROGA_INTERVENCION ',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,150,'FIRMA Y APROBACION DELEGADO  - RESOLUCION_PRORROGA_INTERVENCION ',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,160,'FIRMA Y APROBACION SUPERINTENDENTE  - RESOLUCION_PRORROGA_INTERVENCION ',845,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,170,'FIRMA Y APROBACION LIDER - RESOLUCION_LEVANTAMIENTO_INTERVENCION',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,180,'FIRMA Y APROBACION DELEGADO  - RESOLUCION_LEVANTAMIENTO_INTERVENCION',840,'ASG','S','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,190,'FIRMA Y APROBACION SUPERINTENDENTE  - RESOLUCION_LEVANTAMIENTO_INTERVENCION',845,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,300,'APROBACION DELEGADO  INFORME FINAL',840,'ASG','S','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,310,'GENRACION INFORME SEMANAL ',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,320,'APROBACION DELEGADO  INFORME INTERVEN CION ',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,835,340,'AVISO CONVOCATORIA DE AUDIENCIA PUBLICA DE RECLAMACIONES',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,200,'FIRMA SUPERINTENDENTE RESOLUCION_LEVANTAMIENTO_INTERVENCION',845,'XRP','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,210,'FIRMA SUPERINTENDENTE  RESOLUCION_PRORROGA_INTERVENCION',845,'XRP','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,220,'FIRMA DELEGADO RESOLUCION_LEVANTAMIENTO_INTERVENCION',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,250,'FIRMA DELEGADO RESOLUCION_PRORROGA_INTERVENCION',840,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,260,'FIRMA SUPERINTENDENTE RESOLUCION_LEVANTAMIENTO_INTERVENCION',845,'XRP','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,270,'FIRMA SUPERINTENDENTE  RESOLUCION_PRORROGA_INTERVENCION',845,'XRP','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,300,'INFORME FINAL ENVIO VISITADOR ',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,840,320,'INTERVENCION – INFORME INTERVENCION GRADO 3 Plan de Mejoramiento o plan de seguimiento Revisa Firma',850,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,845,10,'FIRMA SUPERINTENDENTE RESOLUCION_LEVANTAMIENTO_INTERVENCION',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/
INSERT INTO SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE, ID_PROCESO, ID_SUBPROCESO, VERSION_SUBPROCESO, ID_ETAPA_ORIGEN, ID_MOTIVO, DESCRIPCION, ID_ETAPA_POSTERIOR, ESTADO_ACTIVIDAD, INDICADOR_DEVOLUCION, TIPO_COMPUERTA_LLEGADA, FLUJO_DEFECTO, DESCRIPTOR_FIN, DECISION_CALIFICACION, ESTADO, ID_USUARIO_CREACION,FECHA_CREACION, IP_CREACION ) 
VALUES(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'62','6',1,845,20,'FIRMA SUPERINTENDENTE RESOLUCION_PRORROGA_INTERVENCION',830,'ASG','N','EXC',NULL,NULL,NULL,'A',USER,SYSTIMESTAMP,NULL);
/