set linesize 555;
set serveroutput on; 
SPOOL NN_INS_SDB_PGN_MOTIVO_TRAMITE.out;   
--------------------------------------------------------------------------------------------------------------------------------
Insert into SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,
ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,
ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION) values 
(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'1','10','1','101','90','SOLICITUD COMPLEMENTACIÓN A OTRO CÍRCULO REGISTRAL','110','XRP','N','EXC',
null,null,null,'A',USER,SYSTIMESTAMP,null,null,null,null);
/
Insert into SDB_PGN_MOTIVO_TRAMITE (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,
ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,
ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,ID_USUARIO_MODIFICACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION) values 
(SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'1','11','1','101','90','SOLICITUD COMPLEMENTACIÓN A OTRO CÍRCULO REGISTRAL','110','XRP','N','EXC',
null,null,null,'A',USER,SYSTIMESTAMP,null,null,null,null);
/