set linesize 555;
set serveroutput on;
SPOOL 01_SDB_PGN_MOTIVO_TRAMITE.out;
------------------------------------------------------------------------------------------------
begin
 insert into SDB_PGN_MOTIVO_TRAMITE
 (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION)
 values
 ( SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'6','1',1,210,30,'ENVIO POR CORREO ELECTRONICO',203,'AUT','N','EXC',NULL,'N',NULL,'A',USER,SYSTIMESTAMP,NULL);
 EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO SDB_PGN_MOTIVO_TRAMITE:6,1,1,210,30,ENVIO POR CORREO ELECTRONICO,203' || SQLERRM);
end;
/
begin
 insert into SDB_PGN_MOTIVO_TRAMITE
 (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION)
 values
 ( SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'6','2',1,210,30,'ENVIO POR CORREO ELECTRONICO',203,'AUT','N','EXC',NULL,'N',NULL,'A',USER,SYSTIMESTAMP,NULL);
 EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO SDB_PGN_MOTIVO_TRAMITE:6,2,1,210,30,ENVIO POR CORREO ELECTRONICO,203' || SQLERRM);
end;
/
begin
 insert into SDB_PGN_MOTIVO_TRAMITE
 (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION)
 values
 ( SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'6','3',1,210,30,'ENVIO POR CORREO ELECTRONICO',203,'AUT','N','EXC',NULL,'N',NULL,'A',USER,SYSTIMESTAMP,NULL);
 EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO SDB_PGN_MOTIVO_TRAMITE:6,3,1,210,30,ENVIO POR CORREO ELECTRONICO,203' || SQLERRM);
end;
/
begin
 insert into SDB_PGN_MOTIVO_TRAMITE
 (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION)
 values
 ( SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'6','7',1,210,30,'ENVIO POR CORREO ELECTRONICO',203,'AUT','N','EXC',NULL,'N',NULL,'A',USER,SYSTIMESTAMP,NULL);
 EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO SDB_PGN_MOTIVO_TRAMITE:6,7,1,210,30,ENVIO POR CORREO ELECTRONICO,203' || SQLERRM);
end;
/
begin
 insert into SDB_PGN_MOTIVO_TRAMITE
 (ID_MOTIVO_TRAMITE,ID_PROCESO,ID_SUBPROCESO,VERSION_SUBPROCESO,ID_ETAPA_ORIGEN,ID_MOTIVO,DESCRIPCION,ID_ETAPA_POSTERIOR,ESTADO_ACTIVIDAD,INDICADOR_DEVOLUCION,TIPO_COMPUERTA_LLEGADA,FLUJO_DEFECTO,DESCRIPTOR_FIN,DECISION_CALIFICACION,ESTADO,ID_USUARIO_CREACION,FECHA_CREACION,IP_CREACION)
 values
 ( SEC_PGN_MOTIVO_TRAMITE_ID_MOTIVO_TRAMITE.nextval,'6','8',1,210,30,'ENVIO POR CORREO ELECTRONICO',203,'AUT','N','EXC',NULL,'N',NULL,'A',USER,SYSTIMESTAMP,NULL);
 EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR INSERTANDO SDB_PGN_MOTIVO_TRAMITE:6,8,1,210,30,ENVIO POR CORREO ELECTRONICO,203' || SQLERRM);
end;
/
