set linesize 555;
set serveroutput on;
SPOOL 02_UPDATE_SDB_PGN_MOTIVO_TRAMITE.out;
------------------------------------------------------------------------------------------------
BEGIN
  UPDATE SDB_PGN_MOTIVO_TRAMITE
  SET DESCRIPCION = 'CREACION DE MATRICULA EXITOSA PARA CERTIFICADOS'
  ,ID_USUARIO_MODIFICACION = USER
  ,FECHA_MODIFICACION = SYSTIMESTAMP
  ,IP_MODIFICACION = NULL
  WHERE ID_PROCESO = '1'
  AND ID_SUBPROCESO = '14'
  AND VERSION_SUBPROCESO = 1
  AND ID_ETAPA_ORIGEN = 110
  AND ID_MOTIVO = 440
  AND ID_ETAPA_POSTERIOR = 310;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR ACTUALIZANDO DESCRIPCION EN SDB_PGN_MOTIVO_TRAMITE: ID_PROCESO = 1 AND ID_SUBPROCESO = 14 AND VERSION_SUBPROCESO = 1 AND ID_ETAPA_ORIGEN = 110 AND ID_MOTIVO = 440 AND ID_ETAPA_POSTERIOR = 310');
END;
/

