prompt Instalador general
--
-- ACTUALIZACIONES
--
prompt *******************
prompt * ACTUALIZACIONES *
prompt *******************
prompt Ejecutando 01_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\01_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 02_SDB_ACC_COMPLETITUD_DOCUMENTAL_SINONIMO
@@ACTUALIZACIONES\02_SDB_ACC_COMPLETITUD_DOCUMENTAL_SINONIMO.sql
prompt Ejecutando 03_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\03_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 04_SDB_ACC_SUBPROCESO_DML
@@ACTUALIZACIONES\04_SDB_ACC_SUBPROCESO_DML.sql
prompt Ejecutando 05_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\05_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 06_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\06_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 07_sdb_pgn_motivo_tramite_dml
@@ACTUALIZACIONES\07_sdb_pgn_motivo_tramite_dml.sql
prompt Ejecutando 08_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\08_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 09_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\09_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 10_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\10_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 11_INSERT_SDB_PGN_ETAPA
@@ACTUALIZACIONES\11_INSERT_SDB_PGN_ETAPA.sql
prompt Ejecutando 12_INSERT_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\12_INSERT_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 13_INSERT_SDB_PGN_ETAPA
@@ACTUALIZACIONES\13_INSERT_SDB_PGN_ETAPA.sql
prompt Ejecutando 14_INSERT_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\14_INSERT_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 15_INSERT_SDB_PGN_ETAPA
@@ACTUALIZACIONES\15_INSERT_SDB_PGN_ETAPA.sql
prompt Ejecutando 16_INSERT_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\16_INSERT_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 17_UP_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\17_UP_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 18_INSERT_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\18_INSERT_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 19_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\19_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 20_SDB_PGN_ETAPA_DML
@@ACTUALIZACIONES\20_SDB_PGN_ETAPA_DML.sql
prompt Ejecutando 21_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\21_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 22_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\22_SDB_PGN_MOTIVO_TRAMITE.DML.sql
prompt Ejecutando 23_SDB_ACC_SUBPROCESO_DML
@@ACTUALIZACIONES\23_SDB_ACC_SUBPROCESO_DML.sql
prompt Ejecutando 24_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\24_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 25_INS_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\25_INS_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 26_UPD_SDB_PGN_MOTIVO_TRAMITE_DML
@@ACTUALIZACIONES\26_UPD_SDB_PGN_MOTIVO_TRAMITE_DML.sql
prompt Ejecutando 27_UPD_SDB_PGN_ETAPA_DML
@@ACTUALIZACIONES\27_UPD_SDB_PGN_ETAPA_DML.sql
prompt Ejecutando 28_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\28_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 29_INSERT_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\29_INSERT_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 30_UPDATE_SDB_PGN_MOTIVO_TRAMITE
@@ACTUALIZACIONES\30_UPDATE_SDB_PGN_MOTIVO_TRAMITE.sql
prompt Ejecutando 31_SDB_PGN_UNIDAD_TIEMPO_VENCIMIENTO
@@ACTUALIZACIONES\31_SDB_PGN_UNIDAD_TIEMPO_VENCIMIENTO.sql
prompt Ejecutando 32_SDB_PGN_MOTIVO_TRAMITE_REGLA_TRABAJO
@@ACTUALIZACIONES\32_SDB_PGN_MOTIVO_TRAMITE_REGLA_TRABAJO.sql
--
-- DISPARADORES
--
prompt *******************
prompt *  DISPARADORES   *
prompt *******************
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_ACUMULADO
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_ACUMULADO.sql
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_INS_AFTER
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_INS_AFTER.sql
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_INS_BEFORE
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_INS_BEFORE.sql
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_UA_CREA_ETAPA_FECHA_FINAL
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_UA_CREA_ETAPA_FECHA_FINAL.sql
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_UPD_AFTER
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_UPD_AFTER.sql
prompt Ejecutando TRG_SDB_ACC_TURNO_HIST_UPD_BEFORE
@@DISPARADORES\TRG_SDB_ACC_TURNO_HIST_UPD_BEFORE.sql
prompt Ejecutando TRG_SDB_PGN_ETAPA_AUD_IUD_AFTER
@@DISPARADORES\TRG_SDB_PGN_ETAPA_AUD_IUD_AFTER.sql
--
-- PAQUETES
--
prompt *******************
prompt *    PAQUETES     *
prompt *******************
prompt Ejecutando PKG_WORKFLOW_1
@@DISPARADORES\PKG_WORKFLOW_1.sql
prompt Ejecutando PKG_WORKFLOW
@@DISPARADORES\PKG_WORKFLOW.sql